# Generated by Django 4.0.6 on 2022-08-17 15:51

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Madklub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('diet', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('meat', 'Meat')], default='vegetarian', max_length=10), size=None)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
