# Generated by Django 4.0.6 on 2022-08-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madklubModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='madklub',
            name='guests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
