# Generated by Django 4.0.6 on 2022-08-18 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('madklubModel', '0003_alter_madklub_date_alter_madklub_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madklub',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
