# Generated by Django 4.0.6 on 2022-08-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madklubModel', '0004_alter_madklub_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='madklub',
            options={'ordering': ('date',)},
        ),
    ]
