# Generated by Django 4.0.6 on 2022-08-21 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('madklubModel', '0006_remove_madklub_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madklub',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='madklub',
            name='meat_participants',
        ),
        migrations.RemoveField(
            model_name='madklub',
            name='vegan_participants',
        ),
        migrations.RemoveField(
            model_name='madklub',
            name='vegetarian_participants',
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_preference', models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('meat', 'Meat')], default='vegetarian', max_length=10)),
                ('number_guests', models.PositiveIntegerField(default=0)),
                ('madklub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madklub', to='madklubModel.madklub')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
