# Generated by Django 4.0.6 on 2022-08-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madklubModel', '0008_meatparticipants_veganparticipants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madklub',
            name='meat_participants',
        ),
        migrations.AddField(
            model_name='madklub',
            name='meat_participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='meat_participants', to='madklubModel.meatparticipants'),
        ),
        migrations.RemoveField(
            model_name='madklub',
            name='vegan_participants',
        ),
        migrations.AddField(
            model_name='madklub',
            name='vegan_participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='vegan_participants', to='madklubModel.veganparticipants'),
        ),
        migrations.RemoveField(
            model_name='madklub',
            name='vegetarian_participants',
        ),
        migrations.AddField(
            model_name='madklub',
            name='vegetarian_participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='vegetarian_participants', to='madklubModel.vegetarianparticipants'),
        ),
    ]
