# Generated by Django 4.0.6 on 2022-08-21 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('madklubModel', '0009_remove_madklub_meat_participants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_preference', models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('meat', 'Meat')], default='vegetarian', max_length=10)),
                ('number_guests', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='veganparticipants',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='vegetarianparticipants',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='madklub',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='madklub',
            name='meat_participants',
        ),
        migrations.RemoveField(
            model_name='madklub',
            name='vegan_participants',
        ),
        migrations.RemoveField(
            model_name='madklub',
            name='vegetarian_participants',
        ),
        migrations.DeleteModel(
            name='MeatParticipants',
        ),
        migrations.DeleteModel(
            name='VeganParticipants',
        ),
        migrations.DeleteModel(
            name='VegetarianParticipants',
        ),
        migrations.AddField(
            model_name='registration',
            name='madklub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='madklubModel.madklub'),
        ),
        migrations.AddField(
            model_name='registration',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
