# Generated by Django 4.0.6 on 2022-08-21 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('madklubModel', '0010_registration_remove_veganparticipants_participant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.PositiveIntegerField(default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meat_participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VeganParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.PositiveIntegerField(default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegan_participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VegetarianParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.PositiveIntegerField(default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetarian_participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.AddField(
            model_name='madklub',
            name='meat_participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='meat_participants', to='madklubModel.meatparticipants'),
        ),
        migrations.AddField(
            model_name='madklub',
            name='vegan_participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='vegan_participants', to='madklubModel.veganparticipants'),
        ),
        migrations.AddField(
            model_name='madklub',
            name='vegetarian_participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='vegetarian_participants', to='madklubModel.vegetarianparticipants'),
        ),
    ]
