# Generated by Django 4.0.6 on 2022-08-22 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyUser', '0001_initial'),
        ('madklubModel', '0011_meatparticipants_veganparticipants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Madklub_Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.SmallIntegerField(default=0)),
                ('diet', models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('meat', 'Meat')], default='vegetarian', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='veganparticipants',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='vegetarianparticipants',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='madklub',
            name='meat_participants',
        ),
        migrations.RemoveField(
            model_name='madklub',
            name='vegan_participants',
        ),
        migrations.RemoveField(
            model_name='madklub',
            name='vegetarian_participants',
        ),
        migrations.AddField(
            model_name='madklub',
            name='participants',
            field=models.ManyToManyField(blank=True, through='madklubModel.Madklub_Participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MeatParticipants',
        ),
        migrations.DeleteModel(
            name='VeganParticipants',
        ),
        migrations.DeleteModel(
            name='VegetarianParticipants',
        ),
        migrations.AddField(
            model_name='madklub_participant',
            name='madklub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madklub', to='madklubModel.madklub'),
        ),
        migrations.AddField(
            model_name='madklub_participant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
