# Generated by Django 4.0.6 on 2022-08-23 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('madklubModel', '0013_madklubparticipant_alter_madklub_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madklub',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='madklubparticipant',
            name='madklub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madklubModel.madklub'),
        ),
        migrations.AlterField(
            model_name='madklubparticipant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
